apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: consul-demo
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: consul-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
      annotations:
        # Required annotation in order to inject the envoy sidecar proxy:
        consul.hashicorp.com/connect-inject: "true"
        ## Comma separated list of Consul service tags:
        ## Needs to be one line and no spaces,
        ## but can split long lines with \ in YAML:
        consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.whoami.entrypoints=websecure,\
          traefik.http.routers.whoami.rule=Host(`whoami-consul.k3s-sys.stardust.plenuspyramis.com`)"
    spec:
      containers:
      - image: containous/whoami
        name: whoami
        ports:
        - containerPort: 80
          name: web
