apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - consul-demo-namespace.yaml
  - consul-demo-whoami.yaml
  - consul-demo-service-defaults.yaml
  - consul-demo-service-intentions.yaml

