apiVersion: logs.vdp.vmware.com/v1beta1
kind: FluentdConfig
metadata:
  name: fd-config
  namespace: fluentd-system
spec:
  fluentconf: |
    ### Globally match ALL pods in ALL namespaces and upload to S3:
    ### [Year]/[Month]/[Day]/[namespace]/[pod_name]/[timestamp]-[container_name].log
    ### NOTE: this prevents any other kube.** match!
    <match kube.**>
      @type s3
      s3_endpoint ${S3_ENDPOINT}
      s3_bucket ${S3_BUCKET}
      aws_key_id ${S3_ACCESS_KEY}
      aws_sec_key ${S3_SECRET_KEY}
      path "${S3_BASE_DIRECTORY}/logs"
      s3_object_key_format %{path}/%Y/%m/%d/${$.kubernetes.namespace_name}/${$.kubernetes.pod_name}/%Y-%m-%d-%H%M-${$.kubernetes.namespace_name}_${$.kubernetes.pod_name}_${$.kubernetes.container_name}_%{index}.log
      <buffer time,$.kubernetes.namespace_name,$.kubernetes.container_name,$.kubernetes.pod_name>
        path /var/log/fluentd/_s3_buffers
        @type file
        timekey 120
        timekey_wait 10s
        timekey_use_utc true # use utc
      </buffer>
    </match>

    <format>
      @type json
    </format>

