## Find the right network CIDR: docker network inspect -f '{{.IPAM.Config}}' kind
## Edit the IP range below for your correct network CIDR:
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.255.10-172.18.255.250
