apiVersion: logs.vdp.vmware.com/v1beta1
kind: FluentdConfig
metadata:
  name: fd-config
  namespace: fluentd-demo
spec:
  fluentconf: |
    <match kube.fluentd-demo.**>
      @type my_s3
    </match>
