# Traefik Helm values
image:
  name: traefik
  tag: "v2.5"
persistence:
    enabled: true
additionalArguments:
  - "--log.level=DEBUG"
  ## Forward all HTTP to HTTPs
  #- "--entrypoints.web.http.redirections.entryPoint.to=:443"
deployment:
  initContainers:
    ## volume-permissions makes sure /data volume is owned by the traefik security context 65532
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chown -R 65532:65532 /data && chmod -Rv 600 /data && chmod 700 /data"]
      volumeMounts:
        - name: data
          mountPath: /data
    ## DEBUG: add a sleep before Traefik starts, to manually fix volumes etc.
    # - name: sleep
    #   image: alpine:3
    #   command: ["sh", "-c", "sleep 9999999"]
    #   volumeMounts:
    #     - name: data
    #       mountPath: /data
ports:
  ## Add the wildcard certificate to the entrypoint, then all routers inherit it:
  ## https://doc.traefik.io/traefik/routing/entrypoints/#tls
  websecure:
    tls:
      enabled: true
