apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-test
  namespace: traefik-system
spec:
  routes:
  - kind: Rule
    #match: HostRegexp(`whoami.traefik-system.{domain:.*}`)
    match: Host(`$WHOAMI_DOMAIN`)
    services:
    - name: whoami-test
      port: 80
