apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: digitalocean-dns
spec:
  acme:
    email: ${ACME_EMAIL}
    server: ${ACME_CA_SERVER}
    privateKeySecretRef:
      name: digitalocean-dns-acme-account-key
    solvers:
    - selector:
        dnsZones:
          - ${ACME_ZONE}
    - dns01:
        cnameStrategy: Follow
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
